### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by PeterPan73** [jcalado/obsn-invite#2]
Congratulations on your unique work. Well done!
Is it possible that there is a qr code in the generator with options for download?
Thanks.

**Comment by jcalado** [comment]
Hi! Thank you.

I'll work on it and get back to you when done.

**Comment by jcalado** [comment]
https://github.com/jcalado/vdon-invite/commit/83d138675567d7f7dcc6e452f65ff90292684ba3 should add QR Code support

**Comment by jcalado** [comment]
Also steve has now synced up with the repo, so https://invite.vdo.ninja/ now also generates QR Codes.

Thanks for the request!
